[project]
name = "tweet-project"
version = "0.1.0"

[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["tweet_analysis*"]
